name: Update Current Practice

on:
  workflow_dispatch:
  push:
    branches: [ evaluator ]
  pull_request:

jobs:
  test:
    name: Update Current Practice
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Checkout WSCL
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add
    - name: Update Current Practice
      run: |
        for lisp in abcl acl ccl clasp cmucl ecl mkcl sbcl; do
          echo "::group::${lisp}"
          for FILE in wscl-issues/draft/*; do
            lisp -i $lisp -e "(ql:quickload :wscl-evaluator)" -e "(wscl-evaluator:eval-issues \"$FILE\")"
          done
          echo "::endgroup::"        
        done
    - name: diff
      run: |
        git config --global --add safe.directory $(realpath .)
        git diff --output=diff.patch
    - uses: actions/upload-artifact@v4
      with:
        name: diff
        path: diff.patch